CREATE TABLE IF NOT EXISTS list (
    id SERIAL NOT NULL,
    title VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL  DEFAULT NOW(),
    CONSTRAINT list_pkey PRIMARY KEY (id)
);
