CREATE TABLE IF NOT EXISTS item (
    id SERIAL NOT NULL,
    list_id INT4 NOT NULL,
    title VARCHAR(255) NOT NULL,
    done BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL  DEFAULT NOW(),
    CONSTRAINT item_pkey PRIMARY KEY (id),
	CONSTRAINT item_list_id_fkey FOREIGN KEY (list_id) REFERENCES list(id)
);
